apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay-mirror.qiniu.com/prometheus/prometheus
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  storage:
    volumeClaimTemplate:
      spec:
        selector:
          matchLabels:
            app: prometheus-prometheus
        resources:
          requests:
            storage: 50Gi
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: v2.7.2
#挂在默认盘
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-prometheus00
  namespace: monitoring
  labels:
    app: prometheus-prometheus
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce # required
  nfs:
    path: /data/k8s-nfs/prometheus/prometheus00
    server: nfs-dev.talkedu.cn
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-prometheus01
  namespace: monitoring
  labels:
    app: prometheus-prometheus
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce # required
  nfs:
    path: /data/k8s-nfs/prometheus/prometheus01
    server: nfs-dev.talkedu.cn