kind: Deployment
apiVersion: apps/v1
metadata:
  name: cce21days-app1-ming19871211
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cce21days-app1-ming19871211
  template:
    metadata:
      labels:
        app: cce21days-app1-ming19871211
    spec:
      containers:
      - name: container-0
        image: '100.125.0.198:20202/f00355482/tanks:v1'
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: default-secret
      affinity: #亲和性配置
        podAntiAffinity: #pod反亲和性配置
          #设置自身的pod之间在节点级别反亲和
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - cce21days-app1-ming19871211
            topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler